//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado : Persona
    {
        public string SecursalAsignada { get; set; }
        public string AdministradorAsignado { get; set; }
        public int NroCaja { get; set; }
        public int BoletosVendidos { get; set; }
    }
}
